version: "3.3"

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ~/mongodb/database:/data/db
    ports:
      - '27017:27017'
    restart: unless-stopped

  web:
    build: .
    container_name: web_server
    ports:
      - '8080:8080'
    links:
      - mongodb
    environment:
      MONGODB_URI: 'mongodb://mongodb:27017'
    depends_on:
      - mongodb